#!/bin/bash
# Simple Agent Schema Update Script
# For development workflow: modify schema -> apply to dev DB -> create migration file

set -e

echo "🤖 Agent Schema Update Workflow"
echo ""

# Check if there are schema changes
if ! git diff --quiet HEAD -- prisma/schema.prisma 2>/dev/null; then
    echo "✅ Schema changes detected in prisma/schema.prisma"
else
    echo "ℹ️  No schema changes detected"
    exit 0
fi

# Step 1: Push changes to development database
echo "🔄 Step 1: Applying schema changes to Railway dev database..."
unset DATABASE_URL
npx prisma db push --skip-generate

# Step 2: Generate updated Prisma client
echo "🔄 Step 2: Generating Prisma client..."
npx prisma generate

# Step 3: Create a migration file for production deployment
TIMESTAMP=$(date +%Y%m%d%H%M%S)
MIGRATION_NAME="schema_update_${TIMESTAMP}"

echo "🔄 Step 3: Creating migration file for production..."

# Use diff to create migration
unset DATABASE_URL
npx prisma migrate diff \
  --from-empty \
  --to-schema-datamodel prisma/schema.prisma \
  --script > temp_migration.sql

# Create migration directory
MIGRATION_DIR="prisma/migrations/${TIMESTAMP}_${MIGRATION_NAME}"
mkdir -p "$MIGRATION_DIR"

# Create the migration file
cat > "$MIGRATION_DIR/migration.sql" << 'EOF'
-- Migration generated by agent schema update
-- This file contains the schema changes for production deployment
EOF

# Add the diff content (only new changes, not full schema)
echo "" >> "$MIGRATION_DIR/migration.sql"
cat temp_migration.sql >> "$MIGRATION_DIR/migration.sql"
rm temp_migration.sql

echo ""
echo "✅ Agent schema update complete!"
echo "📁 Files updated:"
echo "   - Railway dev database (applied)"
echo "   - prisma/schema.prisma (your changes)"
echo "   - $MIGRATION_DIR/migration.sql (generated)"
echo ""
echo "🚀 Next steps:"
echo "   1. Review migration file: $MIGRATION_DIR/migration.sql"
echo "   2. Commit changes: git add prisma/ && git commit -m 'Update schema: [description]'"
echo "   3. Push to deploy to production via GitHub Actions"

# Stage migration files
git add prisma/migrations/